# --- !Ups

CREATE TABLE Document(
  id INTEGER PRIMARY KEY NOT NULL,
  title VARCHAR(500),
  time TIMESTAMP,
  url VARCHAR(1000) NOT NULL ,
  path VARCHAR(1000) NOT NULL ,
  summary VARCHAR(5000) NOT NULL

);


# --- !Downs

DROP TABLE IF EXISTS Document;
